// Sitemap index is generated by app/sitemap.xml/route.ts as a proper
// <sitemapindex> XML response. The Next.js sitemap convention file (default export)
// only generates <urlset> format, which Google does not treat as a sitemap index.
export {};
